### ISSUE TITLE
Check marks differ (minor)

### ISSUE THREAD

**Issue by jmid** [benmandrew/compiler-ci#17]
I've noticed that the check marks used to signal OK differs between the different backends tested.
The is obviously not a major issue - but nevertheless something that made my OCD click :sweat_smile: 

For example, for this PR https://github.com/ocaml-multicore/multicoretests/pull/366
clicking `Details` on `Multicoretests-CI` yields the following under Linux Chromium:

![checkmarks](https://github.com/ocurrent/multicoretests-ci/assets/2655248/2ef9fac3-e99a-4eac-8846-8b0ae2376391)

https://github.com/ocaml-multicore/multicoretests/pull/366/checks?check_run_id=14737229131

Under Chrome on my old MacBook all OK marks are white-on-green, however the three green ones in the above screenshot are smaller, perhaps indicating a different Unicode character being used? :thinking:

**Comment by benmandrew** [comment]
This issue has also appeared in OCaml-CI.

According to the HTML, GitHub seems to be injecting a wrapper `<g-emoji>` tag around some but not all emojis. If the emoji is deemed not to exist, it has a fallback (your white tick) but even if it finds the emoji it still modifies the appearance; you can see in your screenshot one of the red crosses is slightly larger than the others.

It's very annoying! Hopefully I'll find a quick fix.

**Comment by benmandrew** [comment]
This appears to have been a problem on GitHub's end that is now fixed. If it reappears the issue can be reopened.

**Comment by jmid** [comment]
I'm still seeing different checkmarks, so I think this should be reopened:

![checkmarks-take2](https://github.com/ocurrent/multicoretests-ci/assets/2655248/9cca1806-f8f4-42bf-94f9-d74f1e2bb0ee)
